config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'home/index'

  post 'home/index'

  root 'home#index'

  get 'home/about'

  get 'me/pagetest'

  get 'home/about', to: 'home#about', as: 'aboutit'

  get 'home/lumptest'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blob.rb
class Blob < ApplicationRecord
end

app/models/lump.rb
class Lump < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/me_controller.rb
class MeController < ApplicationController

	def pagetest
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<p><%= current_page?(controller: 'home', action: 'about') %></p>
<% if request.env['PATH_INFO']=='/' %>
	<p>We area root</p>
<% else %>
	<p>We area not root</p>
<% end %>

<style>
	
	.custom-button {
		background-image: url("data:image/svg+xml,%3Csvg height='10pt' viewBox='0 0 448 448' width='10pt' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m408 184h-136c-4.417969 0-8-3.582031-8-8v-136c0-22.089844-17.910156-40-40-40s-40 17.910156-40 40v136c0 4.417969-3.582031 8-8 8h-136c-22.089844 0-40 17.910156-40 40s17.910156 40 40 40h136c4.417969 0 8 3.582031 8 8v136c0 22.089844 17.910156 40 40 40s40-17.910156 40-40v-136c0-4.417969 3.582031-8 8-8h136c22.089844 0 40-17.910156 40-40s-17.910156-40-40-40zm0 0'/%3E%3C/svg%3E");
    width: 1.5em;
    height: 1.5em;
    vertical-align: middle;
    content: "";
    background: no-repeat;
    background-size: 100% 100%;
	}

	.button-mesh {
	  padding: 0.25rem 0.75rem;
    font-size: 1.25rem;
    line-height: 1;
    background-color: transparent;
    border: 1px solid transparent;
    border-radius: 0.25rem;
	}

	.my-btn {
		height: 50px;
		width: 50px;  
		background-image: url("data:image/svg+xml,%3Csvg height='32pt' viewBox='0 0 448 448' width='32pt' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m408 184h-136c-4.417969 0-8-3.582031-8-8v-136c0-22.089844-17.910156-40-40-40s-40 17.910156-40 40v136c0 4.417969-3.582031 8-8 8h-136c-22.089844 0-40 17.910156-40 40s17.910156 40 40 40h136c4.417969 0 8 3.582031 8 8v136c0 22.089844 17.910156 40 40 40s40-17.910156 40-40v-136c0-4.417969 3.582031-8 8-8h136c22.089844 0 40-17.910156 40-40s-17.910156-40-40-40zm0 0'/%3E%3C/svg%3E");
		background-repeat:no-repeat;
		background-position: center;
		border-color: pink;
	}

	.my-span {
		display: inline-block;
		height: 50px;
		width: 50px;
	}

	.container-btn
	{
		height: 50px;
		width: 50px;
		background-color: transparent;
	}

</style>

<button class="my-btn"></button>

<button class="container-btn"><span> </span></button>

<p class="my-span"></p>

</br>

<button class="button-mesh custom-button">
</button>

app/views/home/index.html.erb
<h1>Who are you?</h1>
<%= @generated_image_id %>
<p> <%= @generated_image_error %></p>
<% if current_page?('/') %>
	<p>We area root</p>
<% end %>
<% if @generated_image_hash != nil %>
	<%= image_tag(@generated_image_hash["512"]) %>
<% end %>



<%= form_with url: home_index_path, method: "POST", local: true do |form| %>
	<%= form.label "Gender:" %>
	<%= form.select(:gender_id, ['Male','Female']) %>

	<%= form.label "Ethnicity:" %>
	<%= form.select(:ethnic_id, ['White','Black', 'Asian', 'Latino', 'Prefer Not To Say']) %>

	<%= form.label "Hair Color:" %>
	<%= form.select(:hair_id, ['Brown','Blond', 'Black', 'Gray', 'Red']) %>

	<%= form.label "Age:" %>
	<%= form.select(:age_id, ['Infant','Child', 'Young-adult', 'Adult', 'Elderly']) %>
	<%= form.submit %>
<% end %>

app/views/home/lumptest.html.erb
<p><%= @my_lump.name %></p>
<p><%= @my_lump.height %></p>
<p><%= @my_lump.nick_name %></p>
<hr>
<p><%= @my_blob.name%></p>
<p><%= @my_blob.blobby_factor%></p>
<p><%= @my_blob.permeable%></p>